import image1 from "./images/services/item1.jpg";
import image2 from "./images/services/item2.jpg";
import image3 from "./images/services/item3.jpg";
import image4 from "./images/services/item4.jpg";
import image5 from "./images/services/item5.jpg";
import image6 from "./images/services/item6.jpg";
import image7 from "./images/services/item7.jpg";
import image8 from "./images/services/item8.jpg";
import image9 from "./images/services/item9.jpg";
import staff1 from "./images/Spec/spec1.jpg";

export const services = [
    {
        id: 1,
        image: image1,
        title: "Услуги стилиста",
        text: "Все виды стрижек, окрашивание, создание креативного образа",
        wider: false,
        href: "/haircuts",
    },
    {
        id: 2,
        image: image2,
        title: "ногтевой сервис",
        text: "Маникюр, педикюр, покрытие Shellac и Blossom",
        wider: false,
        href: "/manicure",
    },
    {
        id: 3,
        image: image3,
        title: "визаж",
        text: "Вечерний, свадебный, повседневный макияж ",
        wider: true,
        href: "/makeup",
    },
    {
        id: 4,
        image: image4,
        title: "брови и ресницы",
        text: "Ухоженные брови и ресницы за 1 процедуру. Подберем уникальную форму бровей",
        wider: true,
        href: "/makeup",
    },
    {
        id: 5,
        image: image5,
        title: "массаж",
        text: "Классический, расслабляющий, спортивный и другие виды, а так же эндосфера",
        wider: false,
        href: "/massage",
    },
    {
        id: 6,
        image: image6,
        title: "Косметология",
        text: "Эпиляция, депиляция, пилинги, уход и инъекции у проффесиональных мастеров",
        wider: false,
        href: "/aestheticcosmetology",
    },
    {
        id: 7,
        image: image7,
        title: "солярий",
        text: "Подготивоться к отпуску или восполнить недостаток витамина D",
        wider: false,
        href: "/solarium",
    },
    {
        id: 8,
        image: image8,
        title: "Коррекция фигуры lpg",
        text: "Аппаратные коррекции для безупречной фигуры",
        wider: false,
        href: "/endosphere",
    },
    {
        id: 9,
        image: image9,
        title: "перманентный макияж",
        text: "Подчеркнем привлекательные черты или скроем недостатки",
        wider: true,
        href: "/permanentmakeup",
    },
];

export const benefits = [
    {
        id: 1,
        title: "01",
        text: "широкий спектр услуг в одном месте",
    },
    {
        id: 2,
        title: "02",
        text: "медицинская лицензия",
    },
    {
        id: 3,
        title: "03",
        text: "большой выбор инъекционных процедур",
    },
    {
        id: 4,
        title: "04",
        text: "Аппарат эндосфера",
    },
    {
        id: 5,
        title: "05",
        text: "квалифицированные специалисты",
    },
    {
        id: 6,
        title: "06",
        text: "приемлимые цены",
    },
];

export const staff = [
    {
        id: 1,
        image: staff1,
        position: "топ - стилист",
        name: "Иман Бацаева",
        skill1: "5 лет",
        skill2: "женские стрижки, выход из чёрного, колорирования, мелирование, Airtouch, восстановление волос, плетение, свадебные/ вечерние причёски",
        skill3: "курс в Москве",
        skill4: "мастер-класс Георгия Кота",
        skill5: "стрижки",
        skill6: "психология",
    },
    {
        id: 2,
        image: staff1,
        position: "топ - стилист",
        name: "Иман Бацаева",
        skill1: "5 лет",
        skill2: "женские стрижки, выход из чёрного, колорирования, мелирование, Airtouch, восстановление волос, плетение, свадебные/ вечерние причёски",
        skill3: "курс в Москве",
        skill4: "мастер-класс Георгия Кота",
        skill5: "стрижки",
        skill6: "психология",
    },
    {
        id: 3,
        image: staff1,
        position: "топ - стилист",
        name: "Иман Бацаева",
        skill1: "5 лет",
        skill2: "женские стрижки, выход из чёрного, колорирования, мелирование, Airtouch, восстановление волос, плетение, свадебные/ вечерние причёски",
        skill3: "курс в Москве",
        skill4: "мастер-класс Георгия Кота",
        skill5: "стрижки",
        skill6: "психология",
    },
    {
        id: 4,
        image: staff1,
        position: "топ - стилист",
        name: "Иман Бацаева",
        skill1: "5 лет",
        skill2: "женские стрижки, выход из чёрного, колорирования, мелирование, Airtouch, восстановление волос, плетение, свадебные/ вечерние причёски",
        skill3: "курс в Москве",
        skill4: "мастер-класс Георгия Кота",
        skill5: "стрижки",
        skill6: "психология",
    },
    {
        id: 5,
        image: staff1,
        position: "топ - стилист",
        name: "Иман Бацаева",
        skill1: "5 лет",
        skill2: "женские стрижки, выход из чёрного, колорирования, мелирование, Airtouch, восстановление волос, плетение, свадебные/ вечерние причёски",
        skill3: "курс в Москве",
        skill4: "мастер-класс Георгия Кота",
        skill5: "стрижки",
        skill6: "психология",
    },
    {
        id: 6,
        image: staff1,
        position: "топ - стилист",
        name: "Иман Бацаева",
        skill1: "5 лет",
        skill2: "женские стрижки, выход из чёрного, колорирования, мелирование, Airtouch, восстановление волос, плетение, свадебные/ вечерние причёски",
        skill3: "курс в Москве",
        skill4: "мастер-класс Георгия Кота",
        skill5: "стрижки",
        skill6: "психология",
    },
];

export const enrollData = [
    {
        id: 1,
        name: "СТРИЖКИ",
        value1: "Женские стрижки",
        value2: "Мужские стрижки",
        value3: "Детские стрижки",
    },
    {
        id: 2,
        name: "ОКРАШИВАНИЕ",
        value1: "окрашивание",
        value2: "милирование",
        value3: "колорирование",
    },
    {
        id: 3,
        name: "УХОД",
        value1: "МАСКА PRO FIBER LOREAL",
        value2: "ЭКСПРЕСС УХОД ОТ LEBEL",
        value3: "СПА ПРОГРАММА",
    },
    {
        id: 4,
        name: "УКЛАДКИ",
        value1: "УКЛАДКА ПОВСЕДНЕВНАЯ",
        value2: "УКЛАДКА КОКТЕЙЛЬНАЯ",
        value3: "КОСЫ ДЛЯ ДЕВОЧЕК",
    },
    {
        id: 5,
        name: "БИОЗАВИВКА",
        value1: "короткая биозавивка",
        value2: "средняя биозавивка",
        value3: "длинная биозавивка",
    },
    {
        id: 6,
        name: "НОГТЕВОЙ СЕРВИС",
        value1: "женский маникюр",
        value2: "наращивание",
        value3: "педикюр",
    },
    {
        id: 7,
        name: "ВИЗАЖ",
        value1: "макияж",
        value2: "брови",
        value3: "ресницы",
    },
    {
        id: 8,
        name: "ПЕРМАНЕНТНЫЙ МАКИЯЖ",
        value1: "брови",
        value2: "губы",
        value3: "глаза",
    },
    {
        id: 9,
        name: "МАССАЖ",
        value1: "классический массаж",
        value2: "антицеллюлитный массаж",
        value3: "арома массаж",
    },
    {
        id: 10,
        name: "ИНЪЕКЦИОННАЯ КОСМЕТОЛОГИЯ",
        value1: "контурная пластика",
        value2: "биоревитализация",
        value3: "плазмотерапия",
    },
    {
        id: 11,
        name: "ЭСТЕТИЧЕСКАЯ КОСМЕТОЛОГИЯ",
        value1: "чистки",
        value2: "пилинги",
        value3: "маски",
    },
    {
        id: 12,
        name: "АППАРАТНАЯ КОСМЕТОЛОГИЯ",
        value1: "газожидкостный пилинг",
        value2: "радиоволновой лифинг",
        value3: "термолифтинг",
    },
    {
        id: 13,
        name: "",
        value1: "",
        value2: "",
        value3: "",
    },
    {
        id: 14,
        name: "",
        value1: "",
        value2: "",
        value3: "",
    },
];
